layout_spectrum: 0.5412186
color:
  saturation: 0
  brandStrength: 0.2619655
  lightness: 0
  rhythmicContrast: 0
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 1
name: Cavalry
